datasets:
  - key: DATALAKE.DATA_LAKE_CONVERSION
    service: databricks
    type: sql
    query_file: queries/dev/DATA_LAKE_CONVERSION.sql

  - key: DATALAKE.KEPLER_HEATMAPS
    service: databricks
    type: sql
    query_file: queries/dev/KEPLER_HEATMAPS.sql

  - key: DATALAKE.POS_TRANSACTIONS
    service: databricks
    type: sql
    query_file: queries/dev/POS_TRANSACTIONS.sql

  - key: DEPUTY.TEAM_AVAILABILITY
    service: deputy
    type: api
    openapi_file: openapi/deputy.yaml
    endpoint: /api/v1/supervise/employee/QUERY
    method: POST

  - key: DEPUTY.ROSTER_FORECAST
    service: deputy
    type: api
    openapi_file: openapi/deputy.yaml
    endpoint: /api/v1/resource/Roster/QUERY
    method: POST
